In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('winequality-red.csv')

In [3]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [4]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [5]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [6]:
df.duplicated().sum()

240

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

0

# Random Forest Classifier

Spliting the data into training and testing dataset

In [10]:
X = df.drop('quality',axis=1)
y = df['quality']


In [25]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)

In [26]:
from sklearn.ensemble import RandomForestClassifier
RF_model = RandomForestClassifier()

In [27]:
RF_model.fit(X_train,y_train)

RandomForestClassifier()

In [28]:
y_pred = RF_model.predict(X_test)

In [29]:
y_pred

array([6, 6, 6, 5, 6, 5, 5, 6, 6, 7, 5, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6,
       6, 5, 6, 5, 5, 6, 5, 5, 7, 6, 6, 5, 6, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5, 7, 5, 6, 5, 6, 7, 5, 5, 6,
       5, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 7,
       5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5,
       5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 5, 3, 5, 6, 7, 6, 5, 6, 5, 5, 6, 5,
       5, 5, 7, 5, 5, 5, 5, 7, 6, 5, 7, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6,
       6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 6,
       6, 6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5,
       6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 7, 5, 5, 5, 5, 6, 6,
       5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 4, 5, 5,
       5, 6, 6, 7, 5, 7, 5, 5, 6, 5, 6, 6, 6, 7, 6, 6, 6, 7, 6, 6, 5, 5,
       6, 6, 6, 7, 5, 6, 5, 6, 7, 6, 6, 6, 7, 6, 6, 6, 6, 7, 6, 6, 5, 6,
       5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 6, 7, 5, 6,

In [30]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)

In [31]:
print("The accuracy of the model {} is :".format(accuracy))

The accuracy of the model 0.6080178173719376 is :


Hperparameter Tuning

In [21]:
grid_param = {
    "n_estimators":[90,100,115,130],
    'criterion':['gini','entropy'],
    'max_depth': range(1,10,1),
     'min_samples_leaf':range(2,10,1),
     'max_features':['auto','log2']
}

In [32]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=RF_model,param_grid=grid_param,cv=3,verbose=2,n_jobs=-1)

In [33]:
grid_search.fit(X_train,y_train)

Fitting 3 folds for each of 1152 candidates, totalling 3456 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 10),
                         'max_features': ['auto', 'log2'],
                         'min_samples_leaf': range(2, 10),
                         'n_estimators': [90, 100, 115, 130]},
             verbose=2)

In [34]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 4,
 'max_features': 'log2',
 'min_samples_leaf': 9,
 'n_estimators': 130}

In [49]:
RF_model_best_params = RandomForestClassifier(criterion='entropy', max_depth=4, max_features='log2', min_samples_leaf=9, n_estimators=130)

In [50]:
RF_model_best_params.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=4, max_features='log2',
                       min_samples_leaf=9, n_estimators=130)

In [51]:
y_pred_best_params_RF = RF_model_best_params.predict(X_test)

In [52]:
y_pred_best_params_RF

array([6, 6, 6, 5, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 6, 5, 6,
       6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 5, 7, 5, 6, 5, 6, 7, 6, 5, 6,
       5, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6,
       5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 7, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5,
       5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5, 5, 6,
       6, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5,
       6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5, 6, 6, 6,
       5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5,
       5, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5,
       5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 7, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6,

In [53]:
accuracy_score_best_params_RF = accuracy_score(y_test,y_pred_best_params_RF)

In [54]:
accuracy_score_best_params_RF

0.5590200445434298

Bagging Concept

In [43]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification

model_baggibng_svc = BaggingClassifier(base_estimator=SVC(),n_estimators=50,random_state=0).fit(X_train,y_train)

In [44]:
y_predict = model_baggibng_svc.predict(X_test)

In [45]:
y_predict

array([6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 5, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6,
       5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6,
       6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6,
       6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6,

In [46]:
accuracy_score_bagging = accuracy_score(y_test,y_predict)

In [47]:
accuracy_score_bagging

0.4766146993318486

In [42]:
# If we want to use differnt model in the Bagging algorithim you need to use the VotingClassifier method 

In [ ]:
# Use bagging classifier and regressor,voting classifer and regressor